# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec/fixtures/composite_model.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("spec/fixtures/composite_model.proto", :syntax => :proto3) do
    add_message "example.composite_model.User" do
      optional :id, :uint32, 1
      optional :login, :string, 2
      optional :display_name, :string, 3
      optional :avatar_url, :message, 4, "google.protobuf.StringValue"
      optional :birthday, :message, 6, "example.composite_model.Date"
      optional :age, :uint32, 7
      repeated :skills, :string, 8
    end
    add_message "example.composite_model.Date" do
      optional :year, :uint32, 1
      optional :month, :uint32, 2
      optional :day, :uint32, 3
    end
  end
end

module TestFixture
  module CompositeModel
    User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.composite_model.User").msgclass
    Date = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.composite_model.Date").msgclass
  end
end
