# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec/fixtures/extend_initialization_spec.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("spec/fixtures/extend_initialization_spec.proto", :syntax => :proto3) do
    add_message "example.extend_initialization.User" do
      optional :name, :string, 1
    end
  end
end

module TestFixture
  module ExtendInitialization
    User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.extend_initialization.User").msgclass
  end
end
