# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec/fixtures/has_many_through.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("spec/fixtures/has_many_through.proto", :syntax => :proto3) do
    add_message "example.has_many_through.Post" do
      optional :id, :uint64, 1
      optional :title, :string, 2
      optional :body, :string, 3
      repeated :tags, :message, 4, "example.has_many_through.Tag"
    end
    add_message "example.has_many_through.Tag" do
      optional :name, :string, 1
    end
  end
end

module TestFixture
  module HasManyThrough
    Post = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.has_many_through.Post").msgclass
    Tag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.has_many_through.Tag").msgclass
  end
end
