# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec/fixtures/has_many.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("spec/fixtures/has_many.proto", :syntax => :proto3) do
    add_message "example.has_many.User" do
      optional :id, :uint64, 1
      optional :name, :string, 2
      repeated :posts, :message, 3, "example.has_many.Post"
    end
    add_message "example.has_many.Post" do
      optional :id, :uint64, 1
      optional :title, :string, 2
      optional :body, :string, 3
    end
  end
end

module TestFixture
  module HasMany
    User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.has_many.User").msgclass
    Post = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.has_many.Post").msgclass
  end
end
