# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recursive_model.proto

require 'google/protobuf'


descriptor_data = "\n\x15recursive_model.proto\x12\x11\x65xample.recursive\"E\n\nStringList\x12\x0b\n\x03\x63\x61r\x18\x01 \x01(\t\x12*\n\x03\x63\x64r\x18\x02 \x01(\x0b\x32\x1d.example.recursive.StringListB\x19\xea\x02\x16TestFixture::Recursiveb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module TestFixture
  module Recursive
    StringList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.recursive.StringList").msgclass
  end
end
