# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec/fixtures/simple.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("spec/fixtures/simple.proto", :syntax => :proto3) do
    add_message "example.oneof.Message" do
      optional :body, :string, 1
    end
  end
end

module TestFixture
  module Simple
    Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.oneof.Message").msgclass
  end
end
