# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec/fixtures/well_known_types.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("spec/fixtures/well_known_types.proto", :syntax => :proto3) do
    add_message "example.Message" do
      optional :timestamp, :message, 1, "google.protobuf.Timestamp"
      optional :int32_value, :message, 2, "google.protobuf.Int32Value"
      optional :int64_value, :message, 3, "google.protobuf.Int64Value"
      optional :uint32_value, :message, 4, "google.protobuf.UInt32Value"
      optional :uint64_value, :message, 5, "google.protobuf.UInt64Value"
      optional :float_value, :message, 6, "google.protobuf.FloatValue"
      optional :double_value, :message, 7, "google.protobuf.DoubleValue"
      optional :bool_value, :message, 8, "google.protobuf.BoolValue"
      optional :string_value, :message, 9, "google.protobuf.StringValue"
    end
  end
end

module TestFixture
  module WellKnownTypes
    Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.Message").msgclass
  end
end
